# Generated by Django 4.2.24 on 2025-09-29 13:50

from django.db import migrations, models
import django.db.models.deletion
import files.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to=files.models.file_upload_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=100)),
                ('size', models.BigIntegerField()),
                ('hash_value', models.CharField(max_length=150, unique=True)),
                ('hash_type', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['hash_value'], name='files_file_hash_va_b43506_idx'), models.Index(fields=['created_at'], name='files_file_created_22ed95_idx'), models.Index(fields=['file_type'], name='files_file_file_ty_2d7e73_idx'), models.Index(fields=['size'], name='files_file_size_6009e9_idx'), models.Index(fields=['file_type', 'created_at'], name='files_file_file_ty_30c49b_idx'), models.Index(fields=['size', 'created_at'], name='files_file_size_07abae_idx')],
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='files.file')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
